# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ini.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pygame

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create QLabel for the GIF
        self.back_menu_init = QtWidgets.QLabel(self.centralwidget)
        self.back_menu_init.setGeometry(QtCore.QRect(0, 0, 1920, 1000))
        self.back_menu_init.setObjectName("back_menu_init")

        # Load the GIF using QMovie
        self.movie = QtGui.QMovie("RoboInges presenta.gif")
        self.back_menu_init.setMovie(self.movie)
        self.movie.start()

        self.back_menu_init.setScaledContents(True)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(885, 890, 150, 50))
        self.pushButton.setObjectName("pushButton")
        font = QtGui.QFont()
        font.setPointSize(15)  # Change the size as needed
        self.pushButton.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("ROBOmaticas", "ROBOmaticas"))
        self.pushButton.setText(_translate("MainWindow", "¡Adelante!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
